import { Job, Company } from '@/types';

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior AI Engineer',
    company: 'TechFlow AI',
    companyId: '1',
    location: 'San Francisco, CA',
    type: 'full-time',
    remote: true,
    salary: { min: 150000, max: 200000, currency: 'USD' },
    description:
      "Join our team to build cutting-edge AI solutions for enterprise clients. You'll work on machine learning models, natural language processing, and computer vision applications.",
    requirements: [
      '5+ years ML/AI experience',
      'Python, TensorFlow, PyTorch',
      'PhD in Computer Science or related field',
      'Experience with large language models',
    ],
    benefits: [
      'Competitive salary',
      'Equity options',
      'Health insurance',
      'Flexible work hours',
      'Professional development',
    ],
    postedDate: '2024-01-15',
    tags: [
      'Machine Learning',
      'Python',
      'NLP',
      'Computer Vision',
      'Deep Learning',
    ],
    experienceLevel: 'senior',
    isSaved: false,
  },
  {
    id: '2',
    title: 'AI Product Manager',
    company: 'InnovateAI',
    companyId: '2',
    location: 'New York, NY',
    type: 'full-time',
    remote: false,
    salary: { min: 120000, max: 160000, currency: 'USD' },
    description:
      'Lead product strategy for our AI-powered SaaS platform. Work closely with engineering teams to define product roadmap and drive user adoption.',
    requirements: [
      '3+ years product management',
      'Experience with AI/ML products',
      'Strong analytical skills',
      'Excellent communication',
    ],
    benefits: [
      'Competitive salary',
      'Health benefits',
      '401k matching',
      'Stock options',
      'Flexible PTO',
    ],
    postedDate: '2024-01-14',
    tags: ['Product Management', 'AI/ML', 'SaaS', 'Strategy', 'Analytics'],
    experienceLevel: 'mid',
    isSaved: false,
  },
  {
    id: '3',
    title: 'Machine Learning Research Intern',
    company: 'QuantumAI Labs',
    companyId: '3',
    location: 'Boston, MA',
    type: 'internship',
    remote: false,
    salary: { min: 8000, max: 12000, currency: 'USD' },
    description:
      'Research internship focusing on quantum machine learning algorithms. Work on cutting-edge research with leading AI researchers.',
    requirements: [
      'Currently pursuing PhD in ML/AI',
      'Strong mathematical background',
      'Python programming skills',
      'Research experience',
    ],
    benefits: [
      'Stipend',
      'Housing allowance',
      'Research publication opportunities',
      'Networking events',
    ],
    postedDate: '2024-01-13',
    tags: [
      'Research',
      'Quantum Computing',
      'Machine Learning',
      'Python',
      'Mathematics',
    ],
    experienceLevel: 'entry',
    isSaved: false,
  },
  {
    id: '4',
    title: 'AI DevOps Engineer',
    company: 'CloudAI Solutions',
    companyId: '4',
    location: 'Austin, TX',
    type: 'full-time',
    remote: true,
    salary: { min: 130000, max: 170000, currency: 'USD' },
    description:
      'Build and maintain infrastructure for our AI model deployment pipeline. Ensure scalability and reliability of our ML systems.',
    requirements: [
      '3+ years DevOps experience',
      'Kubernetes, Docker',
      'AWS/Azure experience',
      'MLOps knowledge',
      'Python/Go',
    ],
    benefits: [
      'Competitive salary',
      'Remote work',
      'Health insurance',
      'Professional development',
      'Team events',
    ],
    postedDate: '2024-01-12',
    tags: ['DevOps', 'MLOps', 'Kubernetes', 'AWS', 'Python'],
    experienceLevel: 'mid',
    isSaved: false,
  },
  {
    id: '5',
    title: 'AI Ethics Specialist',
    company: 'Responsible AI',
    companyId: '5',
    location: 'Seattle, WA',
    type: 'full-time',
    remote: true,
    salary: { min: 100000, max: 140000, currency: 'USD' },
    description:
      'Ensure our AI systems are fair, transparent, and accountable. Develop ethical guidelines and conduct bias audits.',
    requirements: [
      'Background in ethics/philosophy',
      'Understanding of AI systems',
      'Experience with bias detection',
      'Strong analytical skills',
    ],
    benefits: [
      'Competitive salary',
      'Remote work',
      'Health benefits',
      'Professional development',
      'Impactful work',
    ],
    postedDate: '2024-01-11',
    tags: [
      'AI Ethics',
      'Bias Detection',
      'Transparency',
      'Accountability',
      'Philosophy',
    ],
    experienceLevel: 'mid',
    isSaved: false,
  },
];

export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'TechFlow AI',
    description:
      'Leading provider of AI-powered business intelligence solutions. We help companies make data-driven decisions using advanced machine learning algorithms.',
    industry: 'Artificial Intelligence',
    size: '50-100 employees',
    founded: 2020,
    location: 'San Francisco, CA',
    website: 'https://techflowai.com',
    benefits: [
      'Competitive salary',
      'Equity options',
      'Health insurance',
      'Flexible work hours',
      'Professional development',
    ],
    culture:
      'Fast-paced, innovative, collaborative environment focused on cutting-edge AI research and development.',
    openPositions: 8,
  },
  {
    id: '2',
    name: 'InnovateAI',
    description:
      'Pioneering AI solutions for healthcare, finance, and retail industries. Our platform helps businesses automate complex processes and gain insights.',
    industry: 'AI Software',
    size: '100-250 employees',
    founded: 2019,
    location: 'New York, NY',
    website: 'https://innovateai.com',
    benefits: [
      'Competitive salary',
      'Health benefits',
      '401k matching',
      'Stock options',
      'Flexible PTO',
    ],
    culture:
      'Mission-driven company focused on making AI accessible to businesses of all sizes.',
    openPositions: 12,
  },
  {
    id: '3',
    name: 'QuantumAI Labs',
    description:
      'Research-focused company exploring the intersection of quantum computing and artificial intelligence. We&apos;re pushing the boundaries of what&apos;s possible.',
    industry: 'Quantum Computing',
    size: '25-50 employees',
    founded: 2021,
    location: 'Boston, MA',
    website: 'https://quantumailabs.com',
    benefits: [
      'Research opportunities',
      'Competitive stipend',
      'Conference attendance',
      'Publication support',
    ],
    culture:
      'Academic research environment with focus on breakthrough innovations in quantum AI.',
    openPositions: 5,
  },
  {
    id: '4',
    name: 'CloudAI Solutions',
    description:
      'Enterprise AI platform provider specializing in scalable machine learning infrastructure and MLOps solutions.',
    industry: 'Cloud Computing',
    size: '250-500 employees',
    founded: 2018,
    location: 'Austin, TX',
    website: 'https://cloudaisolutions.com',
    benefits: [
      'Competitive salary',
      'Remote work',
      'Health insurance',
      'Professional development',
      'Team events',
    ],
    culture:
      'Customer-focused company with emphasis on building reliable, scalable AI infrastructure.',
    openPositions: 15,
  },
  {
    id: '5',
    name: 'Responsible AI',
    description:
      'Dedicated to ensuring AI systems are developed and deployed ethically, with focus on fairness, transparency, and accountability.',
    industry: 'AI Ethics',
    size: '25-50 employees',
    founded: 2022,
    location: 'Seattle, WA',
    website: 'https://responsibleai.org',
    benefits: [
      'Competitive salary',
      'Remote work',
      'Health benefits',
      'Professional development',
      'Impactful work',
    ],
    culture:
      'Mission-driven organization focused on making AI technology beneficial for all of humanity.',
    openPositions: 6,
  },
];
